# Generated by Django 5.2.7 on 2025-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='metodo',
            field=models.CharField(default='dicionario', max_length=50),
        ),
    ]
